Feature/041 add last request check
yui666a/laboratory-TA-app pull request #44
Opened 2022-07-17 03:36 UTC by MasayaMatsushita

ログイン状態を定期的にチェックする変数とタイマー関数を追加しました

2022-07-17 04:08 UTC, yui666a reviewed
テスト用コードが残ってるように思います
わざとでしたら教えてください
コメントした以外の部分も同様の指摘があるかと思います

2022-07-17 04:08 UTC, yui666a commented on backend/Messenger/WEB-INF/src/servlet/WhoamI.java
> -		String clientIpAddr = req.getRemoteAddr();
テスト用のままでいいんですか？

2022-07-17 04:08 UTC, yui666a commented on backend/Messenger/login.html
> -<!--					(テスト用)ipアドレス<input type="text" name="pcIpAddr" /> -->
ココもテスト用を無効化し忘れてませんか？

2022-07-17 04:50 UTC, MasayaMatsushita commented
テスト用のコードをコメントアウトしました

2022-07-17 07:09 UTC, yui666a requested changes

2022-07-17 07:09 UTC, yui666a commented on backend/Messenger/login.html
> +					<!-- (テスト用)ipアドレス<input type="text" name="pcIpAddr" />  -->
細かい話ですが，変更がない場合はもとに戻してくれた方が僕は好きです
内容は同じでも変更があったようにGitが認識するので

2022-07-17 07:09 UTC, yui666a commented on backend/Messenger/WEB-INF/src/servlet/WhoamI.java
> -import java.net.InetAddress;
確認だけです．
ここがなくなっても問題ないですか？

2022-07-17 07:09 UTC, yui666a commented on backend/Messenger/WEB-INF/src/servlet/Schedule.java
> +		List<Pc> pcList = StartServlet.getPcList();
ココからインデントズレてるけど戻しましょう！

2022-07-17 07:24 UTC, MasayaMatsushita commented on backend/Messenger/login.html
> +					<!-- (テスト用)ipアドレス<input type="text" name="pcIpAddr" />  -->
ほんとだ、直しておきます

2022-07-17 07:25 UTC, MasayaMatsushita commented on backend/Messenger/WEB-INF/src/servlet/WhoamI.java
> -import java.net.InetAddress;
結構問題ある
本番用でipアドレスを取得するときに使うモジュールなので

2022-07-17 07:25 UTC, MasayaMatsushita commented on backend/Messenger/WEB-INF/src/servlet/Schedule.java
> +		List<Pc> pcList = StartServlet.getPcList();
直しておきます

2022-07-18 03:38 UTC, MasayaMatsushita commented on backend/Messenger/WEB-INF/src/servlet/Schedule.java
> +		List<Pc> pcList = StartServlet.getPcList();
今コード見たんだけど、私の方ではインデントズレてないんだよね...
もう一度コミットします

2022-07-18 03:40 UTC, yui666a commented on backend/Messenger/WEB-INF/src/servlet/Schedule.java
> +		List<Pc> pcList = StartServlet.getPcList();
おそらくタブとスペースを使ってるからかと思います
l. 28はスペース
l. 30はタブですね

2022-07-18 03:41 UTC, yui666a commented on backend/Messenger/WEB-INF/src/servlet/WhoamI.java
> -import java.net.InetAddress;
怖い怖いって！！笑

2022-07-18 03:43 UTC, yui666a commented
@MasayaMatsushita 
下の者から偉そうで申し訳ないですが，
変更箇所をしっかり確認してからaddしてコミットしましょう！

2022-07-18 03:45 UTC, MasayaMatsushita commented
@yui666a 
仰る通りかと思います。
次回以降気をつけます。

2022-07-18 04:04 UTC, MasayaMatsushita commented on backend/Messenger/WEB-INF/src/servlet/Schedule.java
> +		List<Pc> pcList = StartServlet.getPcList();
全然直らないんだけど...
20行目もおかしくなってるし...

2022-07-18 04:08 UTC, MasayaMatsushita commented
これでどうですか？

2022-07-18 05:13 UTC, yui666a approved these changes
細かいこと一杯言ってすみませんでした
ありがとうございます！

2022-07-18 05:13 UTC, merged