Feature/047 modified json data
yui666a/laboratory-TA-app pull request #48
Opened 2022-07-19 23:30 UTC by MasayaMatsushita

今確認したら、正しいインデントになっていたのでプルリク出します。
(昨日のインデントがおかしかったのはなんでだろうね...)

2022-07-20 08:02 UTC, yui666a approved these changes

2022-07-21 01:59 UTC, yui666a requested changes

2022-07-21 01:59 UTC, yui666a commented on backend/Messenger/WEB-INF/src/servlet/LoginServlet.java
> +		if(clientIpAddr.equals("0:0:0:0:0:0:0:1"))) {
なんでここに閉じカッコ追加したんですか？

2022-07-21 04:35 UTC, MasayaMatsushita commented on backend/Messenger/WEB-INF/src/servlet/LoginServlet.java
> +		if(clientIpAddr.equals("0:0:0:0:0:0:0:1"))) {
すいません！ミスです

2022-07-21 05:32 UTC, yui666a approved these changes

2022-07-21 05:32 UTC, merged