Feature/055 place axios file
yui666a/laboratory-TA-app pull request #56
Opened 2022-07-21 06:20 UTC by MasayaMatsushita

2022-07-21 08:02 UTC, yui666a reviewed
ついでにaxiosのリンク書き換えてくれると嬉しいです！
index.htmlのみ読み込んでます

2022-07-21 08:03 UTC, yui666a requested changes
ついでにaxiosのリンク書き換えてくれると嬉しいです！
index.htmlでのみ読み込んでます

さらにいうと，axios.min.jsにバージョン名入れてくれるとさらに分かりやすい

2022-07-22 02:49 UTC, MasayaMatsushita commented
ファイルの名称変更とリンク先の変更を行いました

2022-07-22 10:30 UTC, yui666a approved these changes

2022-07-22 10:30 UTC, merged